<img src="../assets/ga-logo.png" style="float: left; margin: 20px; height: 55px">

# Introduction to `pandas`

---

### About
`pandas` is the most popular python package for managing datasets and is used extensively by data scientists.

### Learning Objectives
- Explore the characteristics of a dataset at a high level with `pandas`.

### Notebook Guide
An exercise in practising:

- Reading data with `pandas`
- Exploring and manipulating data with `pandas`
    - Column operations
    - Filtering
    - Sorting
    - Writing data

# Scenario

You're an analyst working for CoolBricks - a new toy company who wants to compete with LEGO by producing their own bricks and sets. To better understand what kind of sets to create and at what price points, you are tasked with analyzing LEGO's catalogue over time.

The data comes from Kaggle: [https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time](https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time)

We are going to use `pandas` to read and explore this data.

### Business question

What is the biggest set we could build (in terms of number of pieces) and what sort of price would we want to charge?

#### 1. Import `pandas` and read in the LEGO dataset

In [1]:
import pandas as pd 
lego=pd.read_csv('./data/lego.csv')
lego

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,11.0,0.0,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,10.0,0.0,NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,8.0,0.0,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,10.0,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14931,854242-1,Creeper Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN
14932,854243-1,Steve Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN
14933,854244-1,Piglin Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN
14934,854245-1,Fennec Shand Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,88.0,0.0,5.99,NaN,NaN
14935,854246-1,Scout Trooper Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,107.0,0.0,5.99,NaN,NaN

#### 2. So we can focus on just the columns that help answer the question, select only the following columns into a new `DataFrame` variable:

- name
- theme
- number of pieces
- retail price (USD_MSRP)

In [5]:
lego[['Name','Theme','Pieces','USD_MSRP']]

                          Name      Theme  Pieces  USD_MSRP
0                PreSchool Set  PreSchool    16.0       NaN
1                PreSchool Set  PreSchool    20.0       NaN
2               Pre-School Set      Duplo    21.0       NaN
3                PreSchool Set  PreSchool    32.0       NaN
4                    Basic Set  Samsonite   330.0       NaN
...                        ...        ...     ...       ...
14931        Creeper Key Chain       Gear     NaN      5.99
14932          Steve Key Chain       Gear     NaN      5.99
14933         Piglin Key Chain       Gear     NaN      5.99
14934   Fennec Shand Key Chain       Gear     NaN      5.99
14935  Scout Trooper Key Chain       Gear     NaN      5.99

[14936 rows x 4 columns]

#### 3. How many sets have a price greater than $100?

In [8]:
(lego['USD_MSRP'] > 100).sum()

np.int64(380)

#### 4. What are the top 10 sets with the highest number of pieces?

In [9]:
lego.sort_values(by='Pieces', ascending=False).head(10)

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
13559,31203-1,World Map,2021,Art,Art and crafts,Miscellaneous,Normal,Box,7,Retail,11695.0,NaN,2677.0,4.0,249.99,3.0,199.000
13946,10307-1,Eiffel Tower,2022,Icons,Model making,Landmarks,Normal,Box,21,LEGO exclusive,10001.0,NaN,1825.0,4.2,629.99,1.0,624.990
13449,10294-1,Titanic,2021,Icons,Model making,Miscellaneous,Normal,Box,27,LEGO exclusive,9090.0,NaN,3994.0,4.6,679.99,8.0,640.000
12942,10276-1,Colosseum,2020,Icons,Model making,Landmarks,Normal,Box,48,LEGO exclusive,9036.0,NaN,2883.0,4.3,549.99,3.0,399.990
11928,75192-1,Millennium Falcon,2017,Star Wars,Licensed,Ultimate Collector Series,Normal,Box,11,LEGO exclusive,7541.0,8.0,18898.0,4.6,849.99,10.0,700.000
14380,75331-1,The Razor Crest,2022,Star Wars,Licensed,Ultimate Collector Series,Normal,Box,13,LEGO exclusive,6187.0,4.0,2732.0,4.7,599.99,3.0,450.000
14440,10316-1,The Lord of the Rings: Rivendell,2023,Icons,Model making,Licensed,Normal,Box,20,LEGO exclusive,6167.0,21.0,2104.0,4.7,499.99,3.0,420.390
14807,71799-1,NINJAGO City Markets,2023,Ninjago,Action/Adventure,Dragons Rising,Normal,Box,0,LEGO exclusive,6163.0,NaN,8.0,0.0,369.99,0.0,NaN
12369,71043-1,Hogwarts Castle,2018,Harry Potter,Licensed,General,Normal,Box,15,LEGO exclusive,6020.0,28.0,12937.0,4.5,469.99,7.0,350.991
11437,10256-1,Taj Mahal,2017,Creator Expert,Model making,Landmarks,Normal,Box,2,LEGO exclusive,5923.0,NaN,4384.0,4.0,369.99,3.0,404.991

#### 5. Create a new column to measure "price per piece", which should be the price (USD_MSRP) divided by the number of pieces

In [13]:
lego['price_per_piece'] = lego['USD_MSRP'] / lego['Pieces']
lego.head()

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price,price_per_piece
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,11.0,0.0,NaN,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,10.0,0.0,NaN,0.0,NaN,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,8.0,0.0,NaN,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,10.0,0.0,NaN,0.0,NaN,NaN

#### 6. Use this column to find the top 10 most expensive sets by "price per piece"

In [14]:
lego.sort_values(by='price_per_piece', ascending=False).head(10)

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price,price_per_piece
13892,71394-11,Character Pack Series 3 - Complete,2021,Super Mario,Licensed,Character Pack - Series 3,Collection,{Not specified},0,Retail,0.0,10.0,577.0,0.0,4.99,NaN,NaN,inf
13806,66678-1,LEGO Minifigures - Marvel Studios Series {Box ...,2021,Collectable Minifigures,Miscellaneous,Marvel Studios,Random,Box,0,Retail - limited,0.0,NaN,261.0,0.0,29.94,1.0,39.5710,inf
14251,66700-1,LEGO Minifigures - Series 22 {Box of 6 random ...,2022,Collectable Minifigures,Miscellaneous,Series 22,Random,Box,0,Retail - limited,0.0,NaN,115.0,0.0,29.94,1.0,26.1573,inf
9653,45500-1,EV3 Intelligent Brick,2013,Mindstorms,Technical,EV3,Normal,{Not specified},0,LEGO exclusive,1.0,NaN,113.0,0.0,224.95,1.0,160.0000,224.950
6342,9841-1,NXT Intelligent Brick,2006,Mindstorms,Technical,NXT,Normal,{Not specified},0,{Not specified},1.0,NaN,189.0,0.0,169.99,0.0,NaN,169.990
7695,10287-1,Intelligent NXT Brick (Black),2009,Mindstorms,Technical,NXT,Normal,{Not specified},0,{Not specified},1.0,NaN,99.0,0.0,169.99,1.0,180.0000,169.990
13755,45609-1,Small Hub,2021,Education,Educational,SPIKE,Normal,{Not specified},0,{Not specified},2.0,NaN,18.0,0.0,214.95,1.0,219.9500,107.475
9654,45501-1,DC Rechargeable Battery,2013,Education,Educational,Mindstorms,Normal,{Not specified},0,{Not specified},1.0,NaN,179.0,0.0,99.95,0.0,NaN,99.950
8197,9693-1,NXT DC Rechargeable Battery,2010,Education,Educational,NaN,Normal,{Not specified},0,{Not specified},1.0,NaN,106.0,0.0,79.99,1.0,45.9900,79.990
12927,88006-1,Boost Hub,2019,Powered Up,Technical,NaN,Normal,{Not specified},0,{Not specified},1.0,NaN,117.0,0.0,79.99,1.0,50.0000,79.990

#### 7. Narrow the search to show the top 10 most expensive sets by "price per piece" for the "Icons" theme *only*

In [15]:
icons_only = lego[lego['Theme'] == 'Icons']
icons_only.sort_values(by='price_per_piece', ascending=False).head(10)

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price,price_per_piece
13941,10302-1,Optimus Prime,2022,Icons,Model making,Licensed,Normal,Box,7,LEGO exclusive,1508.0,NaN,6910.0,4.3,179.99,8.0,137.6700,0.119357
13943,10304-1,Chevrolet Camaro Z/28 1969,2022,Icons,Model making,Vehicles,Normal,Box,9,LEGO exclusive,1456.0,NaN,3162.0,4.5,169.99,0.0,NaN,0.116751
13450,10295-1,Porsche 911,2021,Icons,Model making,Vehicles,Normal,Box,7,LEGO exclusive,1458.0,NaN,8641.0,4.5,169.99,12.0,131.2500,0.116591
13440,10282-1,Adidas Originals Superstar,2021,Icons,Model making,Adidas,Normal,Box,8,LEGO exclusive,731.0,NaN,4064.0,4.2,79.99,7.0,64.9500,0.109425
13939,10300-1,Back to the Future Time Machine,2022,Icons,Model making,Vehicles,Normal,Box,8,LEGO exclusive,1872.0,2.0,8363.0,4.6,199.99,12.0,159.9440,0.106832
13942,10303-1,Loop Coaster,2022,Icons,Model making,Fairground Collection,Normal,Box,2,LEGO exclusive,3756.0,11.0,2865.0,4.6,399.99,1.0,345.0000,0.106494
14441,10317-1,Land Rover Classic Defender 90,2023,Icons,Model making,Vehicles,Normal,Box,7,LEGO exclusive,2336.0,NaN,631.0,0.0,239.99,0.0,NaN,0.102735
13446,10291-1,Queer Eye – The Fab 5 Loft,2021,Icons,Model making,Licensed,Normal,Box,7,LEGO exclusive,974.0,7.0,3507.0,4.1,99.99,1.0,65.0000,0.102659
12940,10274-1,Ghostbusters ECTO-1,2020,Icons,Model making,Vehicles,Normal,Box,10,LEGO exclusive,2352.0,NaN,10585.0,4.4,239.99,9.0,218.1427,0.102037
13617,40516-1,Everyone is Awesome,2021,Icons,Model making,Miscellaneous,Normal,Box,2,LEGO exclusive,346.0,11.0,9963.0,4.4,34.99,15.0,39.5000,0.101127

#### 8. What are the top 10 cheapest sets by "price per piece" in the "Icons" theme?

In [16]:
icons_only = lego[lego['Theme'] == 'Icons']
icons_only.sort_values(by='price_per_piece', ascending=True).head(10)

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price,price_per_piece
13439,10281-1,Bonsai Tree,2021,Icons,Model making,Botanical Collection,Normal,Box,11,Retail,878.0,NaN,17980.0,4.4,49.99,12.0,31.20,0.056936
14576,40646-1,Daffodils,2023,Icons,Model making,Botanical Collection,Normal,Box,2,Retail,216.0,NaN,2944.0,3.8,12.99,11.0,14.00,0.060139
12942,10276-1,Colosseum,2020,Icons,Model making,Landmarks,Normal,Box,48,LEGO exclusive,9036.0,NaN,2883.0,4.3,549.99,3.0,399.99,0.060867
14438,10314-1,Dried Flower Centrepiece,2023,Icons,Model making,Botanical Collection,Normal,Box,14,Retail,812.0,NaN,2349.0,0.0,49.99,2.0,43.98,0.061564
13946,10307-1,Eiffel Tower,2022,Icons,Model making,Landmarks,Normal,Box,21,LEGO exclusive,10001.0,NaN,1825.0,4.2,629.99,1.0,624.99,0.062993
13443,10284-1,Camp Nou - FC Barcelona,2021,Icons,Model making,Stadiums,Normal,Box,14,LEGO exclusive,5509.0,NaN,1400.0,4.3,349.99,5.0,330.00,0.063531
14437,10313-1,Wildflower Bouquet,2023,Icons,Model making,Botanical Collection,Normal,Box,7,Retail,939.0,NaN,3502.0,4.3,59.99,2.0,47.95,0.063887
13948,10309-1,Succulents,2022,Icons,Model making,Botanical Collection,Normal,Box,21,Retail,771.0,NaN,7180.0,4.3,49.99,3.0,57.00,0.064838
13947,10308-1,Holiday Main Street,2022,Icons,Model making,Winter Village Collection,Normal,Box,28,LEGO exclusive,1514.0,6.0,6474.0,4.1,99.99,13.0,78.82,0.066044
13938,10299-1,Real Madrid - Santiago Bernabéu Stadium,2022,Icons,Model making,Stadiums,Normal,Box,14,LEGO exclusive,5876.0,NaN,550.0,0.0,399.99,0.0,NaN,0.068072

#### 9. Export the `DataFrame` you created in question 2. to a new CSV file.

In [18]:
lego.to_csv('lego_subset.csv', index=False)

### Reflection

What is your answer to the business question? Here it is as a reminder:

> What is the biggest set we could build (in terms of number of pieces) and what sort of price would we want to charge?

Reflect on your experience. How was working with `pandas` compared to other tools you already know?